version: "3.8"

services:
    cam:
        image: alfg/nginx-rtmp
        restart: always
        networks:
            - site
        ports:
            - 3005:80
            - 1935:1935
        volumes:
            - ./html:/usr/local/nginx/html
            - ./prod.conf:/usr/local/nginx/conf/nginx.conf:ro
            # - /etc/letsencrypt/live/kelseywilliams.co/privkey.pem:/etc/letsencrypt/live/kelseywilliams.co/privkey.pem:ro
            # - /etc/letsencrypt/live/kelseywilliams.co/fullchain.pem:/etc/letsencrypt/live/kelseywilliams.co/fullchain.pem:ro

networks:
    site:
        external: true